language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t egoossens/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true egoossens/react-test npm run test

after_success:
    - docker build -t egoossens/multi-client ./client
    - docker build -t egoossens/multi-nginx ./nginx
    - docker build -t egoossens/multi-server ./server
    - docker build -t egoossens/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push egoossens/multi-client
    - docker push egoossens/multi-nginx
    - docker push egoossens/multi-server
    - docker push egoossens/multi-worker
deploy:
    provider: elasticbeanstalk
    region: eu-west-1
    app: multi-docker
    env: MultiDocker-env-1
    bucket_name: elasticbeanstalk-eu-west-1-560657129093
    bucket_path: multi-docker
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY